export class CodexQuotaError extends Error {
  constructor(code, message, details = undefined) {
    super(message);
    this.name = "CodexQuotaError";
    this.code = code;
    this.details = details;
  }
}

export const ERROR_CODES = Object.freeze({
  RUNTIME_INTEGRITY: "E_RUNTIME_INTEGRITY",
  NO_STORE_PACKAGE: "E_NO_STORE_PACKAGE",
  RUNTIME_UNAVAILABLE: "E_CODEX_RUNTIME_UNAVAILABLE",
  RUNNING_WITHOUT_CDP: "E_RUNNING_WITHOUT_CDP",
  CDP_OWNER_MISMATCH: "E_CDP_OWNER_MISMATCH",
  BROWSER_ID_CHANGED: "E_BROWSER_ID_CHANGED",
  RENDERER_SIGNATURE: "E_RENDERER_SIGNATURE",
  ANCHOR_AMBIGUOUS: "E_ANCHOR_AMBIGUOUS",
  LAYOUT_OVERLAP: "E_LAYOUT_OVERLAP",
  APP_SERVER_UNSUPPORTED: "E_APP_SERVER_UNSUPPORTED",
  APP_SERVER_CLOSED: "E_APP_SERVER_CLOSED",
  AUTH_UNSUPPORTED: "E_AUTH_UNSUPPORTED",
  RATE_LIMIT_SCHEMA: "E_RATE_LIMIT_SCHEMA",
  RATE_LIMIT_STALE: "E_RATE_LIMIT_STALE"
});
